function(add_icecream_cpp_lib START_DIR)
  if(EXISTS "${START_DIR}/../icecream-cpp")
    list(APPEND CMAKE_PREFIX_PATH "${START_DIR}/../icecream-cpp")
    find_package(IcecreamCpp)
    include_directories(SYSTEM ${IcecreamCpp_INCLUDE_DIRS})
    return()
  endif()

  file(GLOB ABOVEFOLDERS LIST_DIRECTORIES true "${START_DIR}/../*")

  foreach(ABOVEFOLDER ${ABOVEFOLDERS})
    if(IS_DIRECTORY ${ABOVEFOLDER})
      if (${ABOVEFOLDER} MATCHES "locus_no_pilotus")
        message("IcecreamCpp not found.")
        return()
      else()
        add_icecream_cpp_lib(${ABOVEFOLDER})
      endif()
    endif()
  endforeach()
endfunction()
